build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.18
  amd64: ghcr.io/home-assistant/amd64-base:3.18
  armv7: ghcr.io/home-assistant/armv7-base:3.18
  armhf: ghcr.io/home-assistant/armhf-base:3.18
  i386: ghcr.io/home-assistant/i386-base:3.18
labels:
  org.opencontainers.image.title: Vaillant Genia Air
  org.opencontainers.image.description: Standalone HA addon to control and optimize the Vaillant Genia Air heat pump
  org.opencontainers.image.source: https://github.com/hirofairlane/genia-air-ha
  org.opencontainers.image.licenses: MIT
